/**
 * Regenerates src/styles/themes.css — the NAMED themes that coexist with the
 * default warm theme (generated.css). Each theme in src/lib/themes.ts is emitted
 * as a scoped `[data-theme="<name>"]` block (light) + a COMPOUND `.dark` selector
 * (dark) so it out-specifies the base `.dark` accent block. Only raw primitives
 * (accent/gray ramps + alphas + accent extras) and the theme's own material
 * tokens are re-pointed; the GLOBAL semantic.css aliases and the `@theme inline`
 * utility mapping are untouched, so utilities re-resolve inside the scope with
 * zero component changes.
 *
 * Uses the SAME generateRadixColors the default theme uses, so a theme is just a
 * seed — this is the whole scalability story.
 *
 * Run:  pnpm --filter @workspace/theme gen:themes
 *   or: pnpm dlx tsx packages/theme/scripts/generate-theme-css.ts   (tsx fallback)
 * Re-run after editing src/lib/themes.ts.
 */
import { writeFileSync } from "fs"
import { dirname, join } from "path"
import { fileURLToPath } from "url"

import { generateRadixColors } from "../src/lib/radix-colors"
import { normalizeAccentSeed } from "../src/lib/radix-theme"
import { THEMES, type NamedTheme } from "../src/lib/themes"

// Same color-mix alpha approximations the default generator emits. Re-declared
// PER SCOPE so `var(--accent-9)` resolves to the theme's accent (a composed
// property declared at :root would "lock" to the root accent — the CSS custom-
// property gotcha), not the base one.
const ACCENT_A = [2, 4, 8, 13, 18, 24, 32, 44, 72, 76, 84]
const GRAY_A = [2, 4, 6, 9, 12, 15, 19, 27, 48, 53, 65]

type Gen = ReturnType<typeof generateRadixColors>

const ramp = (values: string[], name: string): string =>
  values.map((v, i) => `  --${name}-${i + 1}: ${v};`).join("\n")

const alphas = (): string => {
  const a = ACCENT_A.map(
    (p, i) =>
      `  --accent-a${i + 1}: color-mix(in oklch, var(--accent-9) ${p}%, transparent);`
  )
  a.push(`  --accent-a12: color-mix(in oklch, var(--accent-12) 92%, transparent);`)
  const g = GRAY_A.map(
    (p, i) =>
      `  --gray-a${i + 1}: color-mix(in oklch, var(--gray-12) ${p}%, transparent);`
  )
  g.push(`  --gray-a12: color-mix(in oklch, var(--gray-12) 92%, transparent);`)
  return a.join("\n") + "\n\n" + g.join("\n")
}

// The literal, non-scale-following accent tokens — must be re-declared in each
// scope or they'd keep the base theme's values.
const accentExtras = (r: Gen, solid: string): string =>
  [
    `  --accent-contrast: ${r.accentContrast};`,
    `  --accent-surface: ${r.accentSurfaceWideGamut};`,
    `  --accent-indicator: ${r.accentScaleWideGamut[8]};`,
    `  --accent-track: ${r.accentScaleWideGamut[8]};`,
    `  --accent-solid: ${solid};`,
  ].join("\n")

const material = (m: Record<string, string>): string =>
  Object.entries(m)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join("\n")

function block(r: Gen, solid: string, mat: Record<string, string>): string {
  return [
    ramp(r.accentScaleWideGamut, "accent"),
    "",
    ramp(r.grayScaleWideGamut, "gray"),
    "",
    alphas(),
    "",
    accentExtras(r, solid),
    "",
    "  /* material tokens (GlassPanel surface, --panel) */",
    material(mat),
  ].join("\n")
}

function themeCss(t: NamedTheme): string {
  const accent = normalizeAccentSeed(t.accent)
  const light = generateRadixColors({
    appearance: "light",
    accent,
    gray: t.graySeedLight,
    background: t.backgroundLight,
  })
  const dark = generateRadixColors({
    appearance: "dark",
    accent,
    gray: t.graySeedDark,
    background: t.backgroundDark,
  })
  const sel = `[data-theme="${t.name}"]`
  // Light block: bare attribute selector. Subtree scoping is by proximity
  // (custom properties inherit); the whole-app case beats :root by source order
  // (themes.css imports after generated.css).
  // Dark block: COMPOUND selectors → specificity (0,2,0), which deterministically
  // out-ranks the base `.dark` accent block (0,1,0). `.dark <sel>` covers a liquid
  // surface inside a dark page; `<sel>.dark` covers one element carrying both.
  return [
    `${sel} {`,
    // In light mode the WDS brand-fill idiom uses the dark accent step (12);
    // in dark it uses the vivid step (9) so on-accent text stays legible.
    block(light, "var(--accent-12)", t.material.light),
    `}`,
    ``,
    `.dark ${sel},`,
    `${sel}.dark {`,
    block(dark, "var(--accent-9)", t.material.dark),
    `}`,
  ].join("\n")
}

const css = `/* AUTO-GENERATED by scripts/generate-theme-css.ts — do not hand-edit.
   Named themes that COEXIST with the default warm theme (generated.css). Each is
   a scoped [data-theme="<name>"] value override; the GLOBAL semantic.css aliases
   and @theme-inline utility mapping are untouched, so utilities re-resolve inside
   the scope with zero class changes. Edit src/lib/themes.ts, then re-run
   \`pnpm --filter @workspace/theme gen:themes\`. */

${THEMES.map(themeCss).join("\n\n")}
`

const outPath = join(
  dirname(fileURLToPath(import.meta.url)),
  "../src/styles/themes.css"
)
writeFileSync(outPath, css)
console.log(
  `Wrote ${outPath} — ${THEMES.length} theme(s): ${THEMES.map((t) => t.name).join(", ")}`
)
