/**
 * Regenerates src/styles/generated.css — the STATIC, pre-hydration fallback for
 * the default (workspace) theme. At runtime <ThemeStylePreview> re-injects the
 * accent + gray scales per tenant; this file provides everything before that
 * runs (and the status scales, which are static-only).
 *
 * It reads the SAME defaults the runtime uses (DEFAULT_THEME + the gray seeds in
 * radix-theme.ts) and runs the SAME generator, so static and runtime never drift.
 *
 * Run:  pnpm --filter @workspace/theme gen:css
 * Re-run after changing the default accent, gray seeds, background, or scaleNames.
 */
import { writeFileSync } from "fs"
import { dirname, join } from "path"
import { fileURLToPath } from "url"

import { DEFAULT_THEME } from "../src/consts"
import { generateRadixColors } from "../src/lib/radix-colors"
import {
  DEFAULT_GRAY_SEED_DARK,
  DEFAULT_GRAY_SEED_LIGHT,
  normalizeAccentSeed,
} from "../src/lib/radix-theme"

// Scales emitted as raw 12-step ramps. `gray` + `accent` come from dedicated
// generator fields; the rest live in allScalesOklch (keyed by name).
const STATUS_SCALES = [
  "mauve",
  "red",
  "blue",
  "grass",
  "amber",
  "green",
  "orange",
  "cyan",
]
const ALL_SCALES = ["accent", "gray", ...STATUS_SCALES]

// Alpha approximations (color-mix) for SSR; runtime injects true Radix alphas.
const ACCENT_A = [2, 4, 8, 13, 18, 24, 32, 44, 72, 76, 84]
const GRAY_A = [2, 4, 6, 9, 12, 15, 19, 27, 48, 53, 65]

const light = generateRadixColors({
  appearance: "light",
  accent: normalizeAccentSeed(DEFAULT_THEME.accentColor),
  gray: DEFAULT_GRAY_SEED_LIGHT,
  background: DEFAULT_THEME.background.value,
})
const dark = generateRadixColors({
  appearance: "dark",
  accent: normalizeAccentSeed(DEFAULT_THEME.accentColor),
  gray: DEFAULT_GRAY_SEED_DARK,
  background: DEFAULT_THEME.background.valueDark,
})

const scaleOf = (
  r: ReturnType<typeof generateRadixColors>,
  name: string
): string[] => {
  if (name === "accent") return r.accentScaleWideGamut
  if (name === "gray") return r.grayScaleWideGamut
  const hit = r.allScalesOklch.find((s: { name: string }) => s.name === name)
  if (!hit) throw new Error(`scale "${name}" missing from generator output`)
  return hit.scale
}

const emitScales = (r: ReturnType<typeof generateRadixColors>): string =>
  ALL_SCALES.map((name) =>
    scaleOf(r, name)
      .map((v, i) => `  --${name}-${i + 1}: ${v};`)
      .join("\n")
  ).join("\n\n")

const emitAccentExtras = (
  r: ReturnType<typeof generateRadixColors>,
  solid: string
): string =>
  [
    `  --accent-contrast: ${r.accentContrast};`,
    `  --accent-surface: ${r.accentSurfaceWideGamut};`,
    `  --accent-indicator: ${r.accentScaleWideGamut[8]};`,
    `  --accent-track: ${r.accentScaleWideGamut[8]};`,
    // Brand button fill (the WDS hue-vs-fill split): the dark navy step in
    // light mode, the vivid step-9 in dark mode (so on-accent stays readable).
    `  --accent-solid: ${solid};`,
  ].join("\n")

const alphaBlock = (): string => {
  const a = ACCENT_A.map(
    (p, i) =>
      `  --accent-a${i + 1}: color-mix(in oklch, var(--accent-9) ${p}%, transparent);`
  )
  a.push(
    `  --accent-a12: color-mix(in oklch, var(--accent-12) 92%, transparent);`
  )
  const g = GRAY_A.map(
    (p, i) =>
      `  --gray-a${i + 1}: color-mix(in oklch, var(--gray-12) ${p}%, transparent);`
  )
  g.push(`  --gray-a12: color-mix(in oklch, var(--gray-12) 92%, transparent);`)
  return a.join("\n") + "\n\n" + g.join("\n")
}

const themeInline = (): string => {
  const lines: string[] = []
  for (const name of ALL_SCALES) {
    for (let i = 1; i <= 12; i++)
      lines.push(`  --color-${name}-${i}: var(--${name}-${i});`)
    lines.push("")
  }
  for (let i = 1; i <= 12; i++)
    lines.push(`  --color-accent-a${i}: var(--accent-a${i});`)
  lines.push("")
  for (let i = 1; i <= 12; i++)
    lines.push(`  --color-gray-a${i}: var(--gray-a${i});`)
  lines.push("")
  lines.push("  --color-accent-contrast: var(--accent-contrast);")
  lines.push("  --color-accent-surface: var(--accent-surface);")
  lines.push("  --color-accent-indicator: var(--accent-indicator);")
  lines.push("  --color-accent-track: var(--accent-track);")
  lines.push("  --color-accent-solid: var(--accent-solid);")
  return lines.join("\n")
}

const css = `/* AUTO-GENERATED by scripts/generate-default-theme-css.ts — do not hand-edit.
   Re-run \`pnpm --filter @workspace/theme gen:css\` after changing the default
   accent, gray seeds, background, or scaleNames (lib/radix-colors.ts).
   Static fallback for the default workspace theme; <ThemeStylePreview> re-injects
   accent + gray per tenant at runtime. */
:root {
  /* Matches DEFAULT_THEME.borderRadius so this static fallback agrees with the
     value ThemeStylePreview injects at runtime — avoids a pre-hydration shift. */
  --radius: ${DEFAULT_THEME.borderRadius.value};

${emitScales(light)}

  /* Alpha fallbacks — approximated via color-mix for SSR / pre-hydration.
     ThemeStylePreview injects the true Radix-computed alpha scales at runtime. */
${alphaBlock()}

${emitAccentExtras(light, "var(--accent-12)")}
}

.dark {
${emitScales(dark)}

${emitAccentExtras(dark, "var(--accent-9)")}
}

@theme inline {
${themeInline()}
}
`

const outPath = join(
  dirname(fileURLToPath(import.meta.url)),
  "../src/styles/generated.css"
)
writeFileSync(outPath, css)
console.log(
  `Wrote ${outPath} (${css.split("\n").length} lines, ${ALL_SCALES.length} scales)`
)
